#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTwo.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Mission")]
	public partial class MissionsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMission(Mission instance);
    partial void UpdateMission(Mission instance);
    partial void DeleteMission(Mission instance);
    #endregion
		
		public MissionsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ProjectTwoContext"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MissionsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MissionsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MissionsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MissionsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Mission> Missions
		{
			get
			{
				return this.GetTable<Mission>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Missions")]
	public partial class Mission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _missionID;
		
		private string _missionName;
		
		private string _missionPresidentName;
		
		private string _missionAddress;
		
		private string _language;
		
		private string _climate;
		
		private string _dominantReligion;
		
		private string _imageRefCountry;
		
		private string _imageRefSecondary;
		
		private string _imageRefTemple;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmissionIDChanging(int value);
    partial void OnmissionIDChanged();
    partial void OnmissionNameChanging(string value);
    partial void OnmissionNameChanged();
    partial void OnmissionPresidentNameChanging(string value);
    partial void OnmissionPresidentNameChanged();
    partial void OnmissionAddressChanging(string value);
    partial void OnmissionAddressChanged();
    partial void OnlanguageChanging(string value);
    partial void OnlanguageChanged();
    partial void OnclimateChanging(string value);
    partial void OnclimateChanged();
    partial void OndominantReligionChanging(string value);
    partial void OndominantReligionChanged();
    partial void OnimageRefCountryChanging(string value);
    partial void OnimageRefCountryChanged();
    partial void OnimageRefSecondaryChanging(string value);
    partial void OnimageRefSecondaryChanged();
    partial void OnimageRefTempleChanging(string value);
    partial void OnimageRefTempleChanged();
    #endregion
		
		public Mission()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_missionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int missionID
		{
			get
			{
				return this._missionID;
			}
			set
			{
				if ((this._missionID != value))
				{
					this.OnmissionIDChanging(value);
					this.SendPropertyChanging();
					this._missionID = value;
					this.SendPropertyChanged("missionID");
					this.OnmissionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_missionName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string missionName
		{
			get
			{
				return this._missionName;
			}
			set
			{
				if ((this._missionName != value))
				{
					this.OnmissionNameChanging(value);
					this.SendPropertyChanging();
					this._missionName = value;
					this.SendPropertyChanged("missionName");
					this.OnmissionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_missionPresidentName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string missionPresidentName
		{
			get
			{
				return this._missionPresidentName;
			}
			set
			{
				if ((this._missionPresidentName != value))
				{
					this.OnmissionPresidentNameChanging(value);
					this.SendPropertyChanging();
					this._missionPresidentName = value;
					this.SendPropertyChanged("missionPresidentName");
					this.OnmissionPresidentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_missionAddress", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string missionAddress
		{
			get
			{
				return this._missionAddress;
			}
			set
			{
				if ((this._missionAddress != value))
				{
					this.OnmissionAddressChanging(value);
					this.SendPropertyChanging();
					this._missionAddress = value;
					this.SendPropertyChanged("missionAddress");
					this.OnmissionAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_language", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string language
		{
			get
			{
				return this._language;
			}
			set
			{
				if ((this._language != value))
				{
					this.OnlanguageChanging(value);
					this.SendPropertyChanging();
					this._language = value;
					this.SendPropertyChanged("language");
					this.OnlanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_climate", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string climate
		{
			get
			{
				return this._climate;
			}
			set
			{
				if ((this._climate != value))
				{
					this.OnclimateChanging(value);
					this.SendPropertyChanging();
					this._climate = value;
					this.SendPropertyChanged("climate");
					this.OnclimateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dominantReligion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string dominantReligion
		{
			get
			{
				return this._dominantReligion;
			}
			set
			{
				if ((this._dominantReligion != value))
				{
					this.OndominantReligionChanging(value);
					this.SendPropertyChanging();
					this._dominantReligion = value;
					this.SendPropertyChanged("dominantReligion");
					this.OndominantReligionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageRefCountry", DbType="VarChar(500)")]
		public string imageRefCountry
		{
			get
			{
				return this._imageRefCountry;
			}
			set
			{
				if ((this._imageRefCountry != value))
				{
					this.OnimageRefCountryChanging(value);
					this.SendPropertyChanging();
					this._imageRefCountry = value;
					this.SendPropertyChanged("imageRefCountry");
					this.OnimageRefCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageRefSecondary", DbType="VarChar(500)")]
		public string imageRefSecondary
		{
			get
			{
				return this._imageRefSecondary;
			}
			set
			{
				if ((this._imageRefSecondary != value))
				{
					this.OnimageRefSecondaryChanging(value);
					this.SendPropertyChanging();
					this._imageRefSecondary = value;
					this.SendPropertyChanged("imageRefSecondary");
					this.OnimageRefSecondaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageRefTemple", DbType="VarChar(500)")]
		public string imageRefTemple
		{
			get
			{
				return this._imageRefTemple;
			}
			set
			{
				if ((this._imageRefTemple != value))
				{
					this.OnimageRefTempleChanging(value);
					this.SendPropertyChanging();
					this._imageRefTemple = value;
					this.SendPropertyChanged("imageRefTemple");
					this.OnimageRefTempleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
