<?xml version="1.0" encoding="utf-8"?><Database Name="Mission" Class="MissionsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\V11.0;Initial Catalog=Mission;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ProjectTwoContext" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Missions" Member="Missions">
    <Type Name="Mission">
      <Column Name="missionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="missionName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="missionPresidentName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="missionAddress" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="language" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="climate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dominantReligion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="imageRefCountry" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="imageRefSecondary" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="imageRefTemple" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>